amazon:
  access:
    key: AKIAJSSZS6I4DFXLAUUQ
    secret-key: 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
  region: eu-west-2
  end-point:
    url: dynamodb.eu-west-2.amazonaws.com
    
server:
  port: 9001
